site_name: BUT R302 Réseaux d'opérateurs 

nav:
  - 'Généralités BGP(format mindmap)': index.md
  - 'Généralités BGP (format texte)': aplat.md
  - 'Commandes BGP': commandes_aplat.mm.md
  - 'Généralités MPLS(format mindmap)': mpls.mm.md
  - 'Généralités MPLS (format texte)': mpls_aplat.mm.md
  - 'Commandes MPLS (format mindmap)': mpls_cmd.mm.md
  - 'Commandes MPLS (format texte)': mpls_cmd_aplat.mm.md
plugins:
  - markmap:
       base_path: docs
       encoding: utf-8

theme:
  name: material
