site_name: BUT R302 Réseaux d'opérateurs 

nav:
  - 'Généralités BGP(mindmap)': index.md
  - 'Généralités BGP(idem que précédemment mais sans mindmap)': aplat.md
#  - 'Mindmap Commandes BGP': commandes.md
  - 'Commandes BGP': commandes_aplat.mm.md
plugins:
  - markmap:
       base_path: docs
       encoding: utf-8

theme:
  name: material
